// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8YLFHcCW9b3rjMxqMewqKVbvVvtCiX34',
    appId: '1:509226925232:web:39d305999334665a4e8f75',
    messagingSenderId: '509226925232',
    projectId: 'ruta-50e39',
    authDomain: 'ruta-50e39.firebaseapp.com',
    storageBucket: 'ruta-50e39.appspot.com',
    measurementId: 'G-41CXY1KB2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRK9gQkIKqsQ9wjVQgrqjvdkumVjsXoIk',
    appId: '1:509226925232:android:e14fa055e6b45bdb4e8f75',
    messagingSenderId: '509226925232',
    projectId: 'ruta-50e39',
    storageBucket: 'ruta-50e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1yUT0p_fdAaQfhb6fdXsZ-OSDqznwb5w',
    appId: '1:509226925232:ios:eeb06d97a3125dc14e8f75',
    messagingSenderId: '509226925232',
    projectId: 'ruta-50e39',
    storageBucket: 'ruta-50e39.appspot.com',
    iosBundleId: 'com.example.rutaUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1yUT0p_fdAaQfhb6fdXsZ-OSDqznwb5w',
    appId: '1:509226925232:ios:eeb06d97a3125dc14e8f75',
    messagingSenderId: '509226925232',
    projectId: 'ruta-50e39',
    storageBucket: 'ruta-50e39.appspot.com',
    iosBundleId: 'com.example.rutaUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8YLFHcCW9b3rjMxqMewqKVbvVvtCiX34',
    appId: '1:509226925232:web:3717d00e68fd86a94e8f75',
    messagingSenderId: '509226925232',
    projectId: 'ruta-50e39',
    authDomain: 'ruta-50e39.firebaseapp.com',
    storageBucket: 'ruta-50e39.appspot.com',
    measurementId: 'G-51CB4X3E5J',
  );
}
